# Capstone Project - Car accident severity

### Applied Data Science Capstone by IBM/Coursera

## Introduction: Business Problem

With the transportation getting more and more convenient, more and more people choose to travel by car. However, traffic accidents are happening more and more frequently as well. Traffic accidents usually result in varying degrees of death and injury, so it is important for people to know the severity of traffic accidents and know how to protect ourselves.

Collisions he most common type of traffic accident, this project is about trying to build a model that could <b>predict the severity of collision</b>. In particular, this project will be targeted to stakeholders who will be driving at high frequency and the traffic accident rescue personnel.

## Data

Based on definition of our problem, factors that will influence our prediction are:

*   PERSONCOUNT
*	PEDCOUNT
*	PEDCYLCOUNT 
*	VEHCOUNT
*   ROADCOND
*   WEATHER
*   LIGHTCOND

Since some of the above data are related to the injuries and deathes of people and vehicles and some are related to the situation of the accident, I decide to choose them to determine the severity code.

But PEDCOUNT and PEDCYLCOUNT are not always noted down and are less relative, so I decide to drop these two statistics.

So the final factors we choose will be:

*   PERSONCOUNT
*	VEHCOUNT
*   ROADCOND
*   WEATHER
*   LIGHTCOND

In [96]:
import pandas as pd
import numpy as np

In [97]:
df=pd.read_csv('Downloads/Data-Collisions.csv')

//anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3057: DtypeWarning: Columns (33) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [98]:
df.head()

SEVERITYCODE           X          Y  OBJECTID  INCKEY  COLDETKEY REPORTNO  \
0             2 -122.323148  47.703140         1    1307       1307  3502005   
1             1 -122.347294  47.647172         2   52200      52200  2607959   
2             1 -122.334540  47.607871         3   26700      26700  1482393   
3             1 -122.334803  47.604803         4    1144       1144  3503937   
4             2 -122.306426  47.545739         5   17700      17700  1807429   

    STATUS      ADDRTYPE   INTKEY  ... ROADCOND                LIGHTCOND  \
0  Matched  Intersection  37475.0  ...      Wet                 Daylight   
1  Matched         Block      NaN  ...      Wet  Dark - Street Lights On   
2  Matched         Block      NaN  ...      Dry                 Daylight   
3  Matched         Block      NaN  ...      Dry                 Daylight   
4  Matched  Intersection  34387.0  ...      Wet                 Daylight   

  PEDROWNOTGRNT  SDOTCOLNUM SPEEDING ST_COLCODE  \
0           NaN         NaN      NaN         10   
1           NaN   6354039.0      NaN         11   
2           NaN   4323031.0      NaN         32   
3           NaN         NaN      NaN         23   
4           NaN   4028032.0      NaN         10   

                                          ST_COLDESC  SEGLANEKEY  \
0                                  Entering at angle           0   
1  From same direction - both going straight - bo...           0   
2                             One parked--one moving           0   
3                   From same direction - all others           0   
4                                  Entering at angle           0   

   CROSSWALKKEY  HITPARKEDCAR  
0             0             N  
1             0             N  
2             0             N  
3             0             N  
4             0             N  

[5 rows x 38 columns]

In [99]:
df.dtypes

SEVERITYCODE        int64
X                 float64
Y                 float64
OBJECTID            int64
INCKEY              int64
COLDETKEY           int64
REPORTNO           object
STATUS             object
ADDRTYPE           object
INTKEY            float64
LOCATION           object
EXCEPTRSNCODE      object
EXCEPTRSNDESC      object
SEVERITYCODE.1      int64
SEVERITYDESC       object
COLLISIONTYPE      object
PERSONCOUNT         int64
PEDCOUNT            int64
PEDCYLCOUNT         int64
VEHCOUNT            int64
INCDATE            object
INCDTTM            object
JUNCTIONTYPE       object
SDOT_COLCODE        int64
SDOT_COLDESC       object
INATTENTIONIND     object
UNDERINFL          object
WEATHER            object
ROADCOND           object
LIGHTCOND          object
PEDROWNOTGRNT      object
SDOTCOLNUM        float64
SPEEDING           object
ST_COLCODE         object
ST_COLDESC         object
SEGLANEKEY          int64
CROSSWALKKEY        int64
HITPARKEDCAR       object
dtype: objec

In [100]:
df.shape

(194673, 38)

In [101]:
df.set_index('OBJECTID')

SEVERITYCODE           X          Y  INCKEY  COLDETKEY REPORTNO  \
OBJECTID                                                                    
1                    2 -122.323148  47.703140    1307       1307  3502005   
2                    1 -122.347294  47.647172   52200      52200  2607959   
3                    1 -122.334540  47.607871   26700      26700  1482393   
4                    1 -122.334803  47.604803    1144       1144  3503937   
5                    2 -122.306426  47.545739   17700      17700  1807429   
6                    1 -122.387598  47.690575  320840     322340  E919477   
7                    1 -122.338485  47.618534   83300      83300  3282542   
9                    2 -122.320780  47.614076  330897     332397  EA30304   
10                   1 -122.335930  47.611904   63400      63400  2071243   
12                   2 -122.384700  47.528475   58600      58600  2072105   
14                   1         NaN        NaN   48900      48900  2024040   
15                   1 -122.333831  47.547371   38800      38800  C654800   
16                   1 -122.356273  47.571375    2771       2771  1211870   
17                   1 -122.323966  47.606374   32800      32800  2128498   
19                   2 -122.317414  47.664028    1212       1212  3507861   
20                   1 -122.337663  47.617510  330878     332378  3838086   
21                   2 -122.344539  47.692012   46300      46300  2023080   
23                   1         NaN        NaN   23000      23000   537838   
24                   2 -122.328270  47.571420  330833     332333  EA29752   
25                   1 -122.383802  47.583715   97100      97100  2894590   
26                   2 -122.292403  47.732847    1347       1347  3608880   
28                   2 -122.313786  47.708535    1323       1323  3502831   
29                   1 -122.318169  47.615837   80000      80000  2882620   
31                   1 -122.337486  47.589746   28700      28700  1213894   
33                   2 -122.279658  47.553405    1268       1268  3672152   
34                   2 -122.312857  47.599218  320932     322432  E926429   
35                   1 -122.330730  47.615450  113300     113300  3346338   
36                   1 -122.385859  47.581191   64700      64700  2798260   
37                   1 -122.304990  47.611474    1083       1083  3605909   
38                   1         NaN        NaN   61500      61500  2607270   
...                ...         ...        ...     ...        ...      ...   
219510               1 -122.345863  47.612991  307577     308857  3811871   
219511               1 -122.330298  47.603233  312117     313537  E885893   
219512               2 -122.328079  47.604161  307692     308972  E851047   
219513               1 -122.320756  47.608656  312289     313709  E872044   
219514               2 -122.355449  47.704720  308575     309855  E872078   
219515               1 -122.357624  47.635956  307792     309072  3578593   
219516               2 -122.302382  47.626759  307985     309265  E869075   
219517               2 -122.355298  47.684382  310417     311717  3751221   
219519               1 -122.320780  47.614076  309594     310874  E881227   
219520               1 -122.335527  47.617434  308698     309978  3812450   
219521               2 -122.322097  47.649615  308342     309622  3693206   
219522               1 -122.312679  47.719414  311117     312437  E881587   
219523               2 -122.380016  47.664879  310911     312231  3751425   
219524               2 -122.340474  47.614496  312179     313599  E885580   
219525               1 -122.337137  47.610709  307834     309114  3811279   
219528               1 -122.302554  47.584099  311697     313057  E886941   
219529               1 -122.298955  47.717456  308019     309299  3767486   
219531               2         NaN        NaN  308990     310270  3811749   
219532               2 -122.306092  47.617881  308532     309812  3814599   
219535

In [102]:
df1.dropna()

SEVERITYCODE  PERSONCOUNT  VEHCOUNT ROADCOND WEATHER LIGHTCOND
0                  2            2         2        2       3         1
1                  1            2         2        2       2         2
2                  1            4         3        1       3         1
3                  1            3         3        1       1         1
4                  2            2         2        2       2         1
5                  1            2         2        1       1         1
6                  1            2         2        2       2         1
7                  2            3         1        1       1         1
8                  1            2         2        1       1         1
9                  2            2         2        1       1         1
10                 1            2         2        1       3         1
11                 1            2         2        1       1         1
12                 1            0         2        2       2         2
13                 1            2         2        2       2         6
14                 2            2         2        1       1         2
16                 2            3         2        1       3         1
17                 1            0         2        1       3         1
18                 2            4         3        1       1         1
19                 1            2         2        1       4         3
20                 2            3         2        1       1         2
21                 2            5         3        1       1         1
22                 1            2         2        1       1         2
23                 1            1         1        3       4         3
24                 2            3         2        1       1         1
25                 2            2         1        1       1         1
26                 1            2         2        2       3         3
27                 1            2         2        1       1         1
28                 1            2         2        1       1         1
29                 1            2         2        1       1         1
30                 1            3         2        2       2         2
...              ...          ...       ...      ...     ...       ...
194640             2            2         1        2       3         7
194641             1            2         2        1       1         1
194642             1            2         2        1       1         1
194643             1            2         2        1       1         2
194644             1            2         2        1       1         4
194645             2            5         2        1       1         2
194647             2            2         1        2       2         4
194648             1            2         2        2       2         2
194649             2            6         3        1       1         2
194650             2            5         5        1       1         1
194651             1            3         1        2       1         2
194652             1            3         2        2       3         4
194653             2            6         6        2       3         2
194656             2            2         1        1       1         1
194657             1            2         2        2       2         2
194658             1            3         3        2       2         2
194659             1            2         2        2       2         2
194660             2            1         1        2       2         8
194661             2            2         2        1       1         1
194662             1            2         2        1       1         4
194663             2            3         2        2       2         1
194664             1            8         3        1       1         1
194665             1            2         2        1       1         1
194666             2            2         2        2       1         1
194667             1            

In [103]:
df1=df[['SEVERITYCODE','PERSONCOUNT','VEHCOUNT','ROADCOND','WEATHER','LIGHTCOND']]
df1.head()

SEVERITYCODE  PERSONCOUNT  VEHCOUNT ROADCOND   WEATHER  \
0             2            2         2      Wet  Overcast   
1             1            2         2      Wet   Raining   
2             1            4         3      Dry  Overcast   
3             1            3         3      Dry     Clear   
4             2            2         2      Wet   Raining   

                 LIGHTCOND  
0                 Daylight  
1  Dark - Street Lights On  
2                 Daylight  
3                 Daylight  
4                 Daylight

In [104]:
df1['ROADCOND'].value_counts()

Dry               124510
Wet                47474
Unknown            15078
Ice                 1209
Snow/Slush          1004
Other                132
Standing Water       115
Sand/Mud/Dirt         75
Oil                   64
Name: ROADCOND, dtype: int64

In [105]:
df1.ROADCOND[df1.ROADCOND == 'Dry'] = 1
df1.ROADCOND[df1.ROADCOND == 'Wet'] = 2
df1.ROADCOND[df1.ROADCOND == 'Unknown'] = 3
df1.ROADCOND[df1.ROADCOND == 'Ice'] = 4
df1.ROADCOND[df1.ROADCOND == 'Snow/Slush'] = 5
df1.ROADCOND[df1.ROADCOND == 'Other'] = 6
df1.ROADCOND[df1.ROADCOND == 'Standing Water'] = 7
df1.ROADCOND[df1.ROADCOND == 'Sand/Mud/Dirt'] = 8
df1.ROADCOND[df1.ROADCOND == 'Oil'] = 9

//anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
//anaconda3/lib/python3.7/site-packages/pandas/core/generic.py:8682: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._update_inplace(new_data)
//anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3325: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  exec(code_obj, self.user_global_ns, self.user_ns)
//anaconda

In [106]:
df1['WEATHER'].value_counts()

Clear                       111135
Raining                      33145
Overcast                     27714
Unknown                      15091
Snowing                        907
Other                          832
Fog/Smog/Smoke                 569
Sleet/Hail/Freezing Rain       113
Blowing Sand/Dirt               56
Severe Crosswind                25
Partly Cloudy                    5
Name: WEATHER, dtype: int64

In [107]:
df1.WEATHER[df1.WEATHER == 'Clear'] = 1
df1.WEATHER[df1.WEATHER == 'Raining'] = 2
df1.WEATHER[df1.WEATHER == 'Overcast'] = 3
df1.WEATHER[df1.WEATHER == 'Unknown'] = 4
df1.WEATHER[df1.WEATHER == 'Snowing'] = 5
df1.WEATHER[df1.WEATHER == 'Other'] = 6
df1.WEATHER[df1.WEATHER == 'Fog/Smog/Smoke'] = 7
df1.WEATHER[df1.WEATHER == 'Sleet/Hail/Freezing Rain'] = 8
df1.WEATHER[df1.WEATHER == 'Blowing Sand/Dirt'] = 9
df1.WEATHER[df1.WEATHER == 'Severe Crosswind'] = 10
df1.WEATHER[df1.WEATHER == 'Partly Cloudy'] =11

//anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
//anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  
//anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
//anaconda3/lib/python3.7/si

In [108]:
df1['LIGHTCOND'].value_counts()

Daylight                    116137
Dark - Street Lights On      48507
Unknown                      13473
Dusk                          5902
Dawn                          2502
Dark - No Street Lights       1537
Dark - Street Lights Off      1199
Other                          235
Dark - Unknown Lighting         11
Name: LIGHTCOND, dtype: int64

In [109]:
df1.LIGHTCOND[df1.LIGHTCOND == 'Daylight'] = 1
df1.LIGHTCOND[df1.LIGHTCOND == 'Dark - Street Lights On'] = 2
df1.LIGHTCOND[df1.LIGHTCOND == 'Unknown'] = 3
df1.LIGHTCOND[df1.LIGHTCOND == 'Dusk'] = 4
df1.LIGHTCOND[df1.LIGHTCOND == 'Dawn'] = 5
df1.LIGHTCOND[df1.LIGHTCOND == 'Dark - No Street Lights'] = 6
df1.LIGHTCOND[df1.LIGHTCOND == 'Dark - Street Lights Off'] = 7
df1.LIGHTCOND[df1.LIGHTCOND == 'Other'] = 8
df1.LIGHTCOND[df1.LIGHTCOND == 'Dark - Unknown Lighting'] = 9

//anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
//anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  
//anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
//anaconda3/lib/python3.7/si

In [126]:
df1.dropna(inplace=True)

//anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [127]:
X = np.asarray(df1[['PERSONCOUNT', 'VEHCOUNT', 'ROADCOND', 'WEATHER', 'LIGHTCOND']])
X[0:5]

array([[2, 2, 2, 3, 1],
       [2, 2, 2, 2, 2],
       [4, 3, 1, 3, 1],
       [3, 3, 1, 1, 1],
       [2, 2, 2, 2, 1]], dtype=object)

In [128]:
y = np.asarray(df1['SEVERITYCODE'])
y [0:5]

array([2, 1, 1, 1, 2])

In [129]:
from sklearn import preprocessing
X = preprocessing.StandardScaler().fit(X).transform(X)
X[0:5]

array([[-0.33905581,  0.05306845,  0.70875343,  1.10587178, -0.59511457],
       [-0.33905581,  0.05306845,  0.70875343,  0.20504641,  0.34710496],
       [ 1.13648946,  1.8466818 , -0.60855849,  1.10587178, -0.59511457],
       [ 0.39871683,  1.8466818 , -0.60855849, -0.69577897, -0.59511457],
       [-0.33905581,  0.05306845,  0.70875343,  0.20504641, -0.59511457]])

In [130]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=4)
print ('Train set:', X_train.shape,  y_train.shape)
print ('Test set:', X_test.shape,  y_test.shape)

Train set: (151469, 5) (151469,)
Test set: (37868, 5) (37868,)


In [131]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
LR = LogisticRegression(C=0.01, solver='liblinear').fit(X_train,y_train)
LR

LogisticRegression(C=0.01, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='liblinear', tol=0.0001, verbose=0,
                   warm_start=False)

In [132]:
yhat = LR.predict(X_test)
yhat

array([1, 1, 1, ..., 1, 1, 1])

In [133]:
yhat_prob = LR.predict_proba(X_test)
yhat_prob

array([[0.69761159, 0.30238841],
       [0.85021833, 0.14978167],
       [0.77419807, 0.22580193],
       ...,
       [0.85596037, 0.14403963],
       [0.78616069, 0.21383931],
       [0.75429639, 0.24570361]])

In [134]:
from sklearn.metrics import jaccard_similarity_score
jaccard_similarity_score(y_test, yhat)

//anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:635: DeprecationWarning: jaccard_similarity_score has been deprecated and replaced with jaccard_score. It will be removed in version 0.23. This implementation has surprising behavior for binary and multiclass classification tasks.
  'and multiclass classification tasks.', DeprecationWarning)


0.6987958170486954

In [135]:
from sklearn.metrics import log_loss
log_loss(y_test, yhat_prob)

0.5851352839636487

In [137]:
from sklearn.metrics import classification_report
print (classification_report(y_test, yhat))

              precision    recall  f1-score   support

           1       0.71      0.97      0.82     26362
           2       0.53      0.08      0.13     11506

    accuracy                           0.70     37868
   macro avg       0.62      0.52      0.48     37868
weighted avg       0.65      0.70      0.61     37868

